name: buildGiteePages
on:
  push:
    branches: 
    - pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: w-yuxuan
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: w-yuxuan/wyx_blog
          branch: pages
