name: syncToGitee
on:
  push:
    branches: 
    - main
    - pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/wyx-lsy
          dst: gitee/w-yuxuan
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "wyx_blog"
          force_update: true
          debug: true
